export default {

    // GET ALL SCOUTS (FOR LIST)
    SCOUTS_LOADING: "SCOUTS_LOADING",
    SCOUTS_LOADED: "SCOUTS_LOADED",
    SCOUTS_LOADING_ERROR: "SCOUTS_LOADING_ERROR",

    // GET AN SCOUT (FOR DETAILS)
    SCOUT_LOADING: "SCOUT_LOADING",
    SCOUT_LOADED: "SCOUT_LOADED",
    SCOUT_LOADING_ERROR: "SCOUT_LOADING_ERROR",

    // CREATE AN SCOUT
    SCOUT_ADDING: "SCOUT_CREATING",
    SCOUT_ADDED: "SCOUT_CREATED",
    SCOUT_ADD_ERROR: "SCOUT_CREATE_ERROR",

    // UPDATE AN SCOUT
    SCOUT_UPDATNG: "SCOUT_UPDATING",
    SCOUT_UPDATED: "SCOUT_UPDATED",
    SCOUT_UPDATE_ERROR: "SCOUT_UPDATE_ERROR",

    // DELETE AN SCOUT
    SCOUT_DELETING: "SCOUT_DELETING",
    SCOUT_DELETED: "SCOUT_DELETED",
    SCOUT_DELETE_ERROR: "SCOUT_DELETE_ERROR",

    // DELETE ALL SCOUTS                        // Don't think we gon need this 
    SCOUTS_DELETING: "SCOUTS_DELETING",
    SCOUTS_DELETED: "SCOUTS_DELETED",
    SCOUTS_DELETE_ERROR: "SCOUTS_DELETE_ERROR",


    // FIND AN SCOUT
    SCOUT_SEARCHING: "SCOUT_SEARCHING",
    SCOUT_SEARCH_FOUND: "SCOUT_SEARCH_FOUND",
    SCOUT_SEARCH_NOTFOUND: "SCOUT_SEARCH_NOTFOUND",
    SCOUT_SEARCH_ERROR: "SCOUT_SEARCH_ERROR",
}