export default {

    // GET ALL EVENTS (FOR LIST)
    EVENTS_LOADING: "EVENTS_LOADING",
    EVENTS_LOADED: "EVENTS_LOADED",
    EVENTS_LOADING_ERROR: "EVENTS_LOADING_ERROR",

    // GET AN EVENT (FOR DETAILS)
    EVENT_LOADING: "EVENT_LOADING",
    EVENT_LOADED: "EVENT_LOADED",
    EVENT_LOADING_ERROR: "EVENT_LOADING_ERROR",

    // CREATE AN EVENT
    EVENT_CREATING: "EVENT_CREATING",
    EVENT_CREATED: "EVENT_CREATED",
    EVENT_CREATE_ERROR: "EVENT_CREATE_ERROR",

    // UPDATE AN EVENT
    EVENT_UPDATNG: "EVENT_UPDATING",
    EVENT_UPDATED: "EVENT_UPDATED",
    EVENT_UPDATE_ERROR: "EVENT_UPDATE_ERROR",

    // DELETE AN EVENT
    EVENT_DELETING: "EVENT_DELETING",
    EVENT_DELETED: "EVENT_DELETED",
    EVENT_DELETE_ERROR: "EVENT_DELETE_ERROR",

    // DELETE ALL EVENTS                        // Don't think we gon need this 
    EVENTS_DELETING: "EVENTS_DELETING",
    EVENTS_DELETED: "EVENTS_DELETED",
    EVENTS_DELETE_ERROR: "EVENTS_DELETE_ERROR",


    // FIND AN EVENT
    EVENT_SEARCHING: "EVENT_SEARCHING",
    EVENT_SEARCH_FOUND: "EVENT_SEARCH_FOUND",
    EVENT_SEARCH_NOTFOUND: "EVENT_SEARCH_NOTFOUND",
    EVENT_SEARCH_ERROR: "EVENT_SEARCH_ERROR",
}