export default {

    // LOG IN 
    LOGGING_IN: "LOGGING_IN",
    LOGGED_IN: "LOGGED_IN",
    LOG_IN_ERROR: "LOG_IN_ERROR",

    // LOG OUT
    LOGGING_OUT: "LOGGING_OUT",
    LOGGED_OUT: "LOGGED_OUT",
    LOG_OUT_ERROR: "LOG_OUT_ERROR",

    // REFRESH TOKEN
    REFRESHING_TOKEN: "REFRESHING_TOKEN",
    TOKEN_REFRESHED: "TOKEN_REFRESHED",
    TOKEN_REFRESH_ERROR: "TOKEN_REFRESH_ERROR",

}