export default {

    // GET ALL ACCEPTEDS (FOR LIST)
    ACCEPTEDS_LOADING: "ACCEPTEDS_LOADING",
    ACCEPTEDS_LOADED: "ACCEPTEDS_LOADED",
    ACCEPTEDS_LOADING_ERROR: "ACCEPTEDS_LOADING_ERROR",

    // GET AN ACCEPTED (FOR DETAILS)
    ACCEPTED_LOADING: "ACCEPTED_LOADING",
    ACCEPTED_LOADED: "ACCEPTED_LOADED",
    ACCEPTED_LOADING_ERROR: "ACCEPTED_LOADING_ERROR",

}