export default {

    // GET ALL CANDIDATES (FOR LIST)
    CANDIDATES_LOADING: "CANDIDATES_LOADING",
    CANDIDATES_LOADED: "CANDIDATES_LOADED",
    CANDIDATES_LOADING_ERROR: "CANDIDATES_LOADING_ERROR",

    // GET AN CANDIDATE (FOR DETAILS)
    CANDIDATE_LOADING: "CANDIDATE_LOADING",
    CANDIDATE_LOADED: "CANDIDATE_LOADED",
    CANDIDATE_LOADING_ERROR: "CANDIDATE_LOADING_ERROR",

    // ACCEPT CANDIDATES
    CANDIDATE_ACCEPTING: "CANDIDATE_ACCEPTING",
    CANDIDATE_ACCEPTED: "CANDIDATE_ACCPTED",
    CANDIDATE_ACCEPT_ERROR: "CANDIDATE_ACCEPT_ERROR",

}
