export default {

    // GET ALL PARAMETERS (FOR LIST)
    PARAMETERS_LOADING: "PARAMETERS_LOADING",
    PARAMETERS_LOADED: "PARAMETERS_LOADED",
    PARAMETERS_LOADING_ERROR: "PARAMETERS_LOADING_ERROR",

    // GET AN PARAMETER (FOR DETAILS)
    PARAMETER_LOADING: "PARAMETER_LOADING",
    PARAMETER_LOADED: "PARAMETER_LOADED",
    PARAMETER_LOADING_ERROR: "PARAMETER_LOADING_ERROR",

    // CREATE AN PARAMETER
    PARAMETER_ADDING: "PARAMETER_CREATING",
    PARAMETER_ADDED: "PARAMETER_CREATED",
    PARAMETER_ADD_ERROR: "PARAMETER_CREATE_ERROR",

    // UPDATE AN PARAMETER
    PARAMETER_UPDATNG: "PARAMETER_UPDATING",
    PARAMETER_UPDATED: "PARAMETER_UPDATED",
    PARAMETER_UPDATE_ERROR: "PARAMETER_UPDATE_ERROR",

    // DELETE AN PARAMETER
    PARAMETER_DELETING: "PARAMETER_DELETING",
    PARAMETER_DELETED: "PARAMETER_DELETED",
    PARAMETER_DELETE_ERROR: "PARAMETER_DELETE_ERROR",

    // DELETE ALL PARAMETERS                        // Don't think we gon need this 
    PARAMETERS_DELETING: "PARAMETERS_DELETING",
    PARAMETERS_DELETED: "PARAMETERS_DELETED",
    PARAMETERS_DELETE_ERROR: "PARAMETERS_DELETE_ERROR",


    // FIND AN PARAMETER
    PARAMETER_SEARCHING: "PARAMETER_SEARCHING",
    PARAMETER_SEARCH_FOUND: "PARAMETER_SEARCH_FOUND",
    PARAMETER_SEARCH_NOTFOUND: "PARAMETER_SEARCH_NOTFOUND",
    PARAMETER_SEARCH_ERROR: "PARAMETER_SEARCH_ERROR",
    
}