export default {

    // GET ALL APPLICANTS (FOR LIST)
    APPLICANTS_LOADING: "APPLICANTS_LOADING",
    APPLICANTS_LOADED: "APPLICANTS_LOADED",
    APPLICANTS_LOADING_ERROR: "APPLICANTS_LOADING_ERROR",

    // GET AN APPLICANT (FOR DETAILS)
    APPLICANT_LOADING: "APPLICANT_LOADING",
    APPLICANT_LOADED: "APPLICANT_LOADED",
    APPLICANT_LOADING_ERROR: "APPLICANT_LOADING_ERROR",

    // APPROVE APPLICANTS
    APPLICANTS_APPROVING: "APPLICANT_APPROVING",
    APPLICANT_APPROVED: "APPLICANT_APPROVED",
    APPLICANT_APPROVE_ERROR: "APPLICANT_APPROVE_ERROR",

}