export default {

    // GET ALL SKILLS (FOR LIST)
    SKILLS_LOADING: "SKILLS_LOADING",
    SKILLS_LOADED: "SKILLS_LOADED",
    SKILLS_LOADING_ERROR: "SKILLS_LOADING_ERROR",

    // GET AN SKILL (FOR DETAILS)
    SKILL_LOADING: "SKILL_LOADING",
    SKILL_LOADED: "SKILL_LOADED",
    SKILL_LOADING_ERROR: "SKILL_LOADING_ERROR",

    // CREATE AN SKILL
    SKILL_ADDING: "SKILL_CREATING",
    SKILL_ADDED: "SKILL_CREATED",
    SKILL_ADD_ERROR: "SKILL_CREATE_ERROR",

    // UPDATE AN SKILL
    SKILL_UPDATNG: "SKILL_UPDATING",
    SKILL_UPDATED: "SKILL_UPDATED",
    SKILL_UPDATE_ERROR: "SKILL_UPDATE_ERROR",

    // DELETE AN SKILL
    SKILL_DELETING: "SKILL_DELETING",
    SKILL_DELETED: "SKILL_DELETED",
    SKILL_DELETE_ERROR: "SKILL_DELETE_ERROR",

    // DELETE ALL SKILLS                        // Don't think we gon need this 
    SKILLS_DELETING: "SKILLS_DELETING",
    SKILLS_DELETED: "SKILLS_DELETED",
    SKILLS_DELETE_ERROR: "SKILLS_DELETE_ERROR",


    // FIND AN SKILL
    SKILL_SEARCHING: "SKILL_SEARCHING",
    SKILL_SEARCH_FOUND: "SKILL_SEARCH_FOUND",
    SKILL_SEARCH_NOTFOUND: "SKILL_SEARCH_NOTFOUND",
    SKILL_SEARCH_ERROR: "SKILL_SEARCH_ERROR",
}