export default {

    // GET MY ACCOUNT (FOR DETAILS)
    ACCOUNT_LOADING: "ACCOUNT_LOADING",
    ACCOUNT_LOADED: "ACCOUNT_LOADED",
    ACCOUNT_LOADING_ERROR: "ACCOUNT_LOADING_ERROR",

    // CREATE MY ACCOUNT
    ACCOUNT_CREATING: "ACCOUNT_CREATING",
    ACCOUNT_CREATED: "ACCOUNT_CREATED",
    ACCOUNT_CREATE_ERROR: "ACCOUNT_CREATE_ERROR",

    // UPDATE MY ACCOUNT
    ACCOUNT_UPDATNG: "ACCOUNT_UPDATING",
    ACCOUNT_UPDATED: "ACCOUNT_UPDATED",
    ACCOUNT_UPDATE_ERROR: "ACCOUNT_UPDATE_ERROR",

    // UPDATE MY LOCAL ACCOUNT
    ACCOUNT_LOCAL_UPDATNG: "ACCOUNT_LOCAL_UPDATING",
    ACCOUNT_LOCAL_UPDATED: "ACCOUNT_LOCAL_UPDATED",
    ACCOUNT_LOCAL_UPDATE_ERROR: "ACCOUNT_LOCAL_UPDATE_ERROR",

    // DELETE MY ACCOUNT
    ACCOUNT_DELETING: "ACCOUNT_DELETING",
    ACCOUNT_DELETED: "ACCOUNT_DELETED",
    ACCOUNT_DELETE_ERROR: "ACCOUNT_DELETE_ERROR",

}